# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            iNRG_cMAP
tagline:          Iterative Network-Guided Connectivity mapping
description:      "Iterative Network-Guided Connectivity mapping"
#url:              https://github.com/saezlab/projectDocumentationTemplate
baseurl:          /iNRG_cMAP/
toollogo:         /iNRG_cMAP/inrg_cmap_logo.jpg

author:
  name:           'Francesco Iorio'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/francescojm/iNRG_cMap
